In [1]:
a = [1,2,3]
b = a
c = [1,2,3]
print(a == b, a == c, a is b, a is c)

True True True False


In [8]:
one = [1, "2", 3, "4"]
two = ("a", "b", "c", "d")
one.append(5)
one.extend(two)
three = two + ("f", 'g')


In [15]:
my_lst = [1, 3, 5]
my_lst = my_lst[:-1]
print(my_lst)

[1, 3]


In [20]:
config = {
    "server": {
        "host": "127.0.0.1",
        "port": "22"
    },
    "configuration": {
        "ssh": {
            "access": True,
            "login": "some",
            "password": "some"
        },
        "name": "2491Oaaf1414"
    }
}
config['configuration']['ssh']['login']

'some'

In [22]:
remaining_time = 76
temperature = 99
print(f'Температура: {temperature}, оставшееся время: {remaining_time}')
#print("Температура: {temperature}, оставшееся время: {remaining_time}".format())
print("Температура: {}, оставшееся время: {}".format(temperature,remaining_time))
print(r'Температура: {temperature}, оставшееся время: {remaining_time}')

Температура: 99, оставшееся время: 76
Температура: 99, оставшееся время: 76
Температура: {temperature}, оставшееся время: {remaining_time}


In [23]:
import numpy as np

In [26]:
n=5
m=5
print(np.ones((n, m)))
print(np.linspace(n, m))
#print(np.zeros(n, m))
print(np.zeros((n, m)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
"""
import os
import pandas as pd

bronze_path = os.path.abspath('bronze_top.csv')
silve_path = os.path.abspath('silver_top.csv')

bronze_top = pd.read_csv(bronze_path, sep=',')
silver_top = pd.read_csv(silve_path, sep=',')

merged = bronze_top.merge(
    silver_top,
    on=['Country'],
    how='inner',
    suffixes=['_bronze','_silver']
    """

In [45]:
products = {'milk': 100.0, 'bread': 50.0, 'salt': 20.0}
stocks = {'bread': "10%", 'milk': "20.9"}
def apply_discounts(products, stocks):
    s_key = stocks.keys()
    for p_key, p_value in products.items():
        if p_key in s_key:
            s_value = float(stocks[p_key].replace('%', ''))
            products[p_key] = round(p_value*(1 - s_value/100), 2)
    return products
res = apply_discounts(products, stocks)
print(res)

{'milk': 79.1, 'bread': 45.0, 'salt': 20.0}


In [47]:
import pandas as pd

In [48]:
solar_data = pd.read_csv('data/solarpower.csv')
solar_data.head()

date  cum_power
0  2017-01-01    20111.0
1  2017-01-02    20112.0
2  2017-01-03    20115.0
3  2017-01-04    20117.0
4  2017-01-05    20119.0

In [56]:
solar_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664 entries, 0 to 663
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       664 non-null    object 
 1   cum_power  664 non-null    float64
dtypes: float64(1), object(1)
memory usage: 10.5+ KB


In [49]:
display(solar_data['cum_power'].value_counts())

 24053.0    3
-1.0        2
 24048.0    2
 24081.0    2
 20208.0    2
           ..
 23080.0    1
 23083.0    1
 23103.0    1
 23108.0    1
 28120.0    1
Name: cum_power, Length: 650, dtype: int64

In [51]:
solar_data['cum_power'] = solar_data['cum_power'].interpolate()

In [52]:
display(solar_data['cum_power'].value_counts())

 24053.0    3
-1.0        2
 24048.0    2
 24081.0    2
 20208.0    2
           ..
 23080.0    1
 23083.0    1
 23103.0    1
 23108.0    1
 28120.0    1
Name: cum_power, Length: 650, dtype: int64

In [55]:
for i in range(len(solar_data['cum_power'])):
    if solar_data['cum_power'][i] == -1:
        solar_data['cum_power'][i] = (solar_data['cum_power'][i-1] + solar_data['cum_power'][i+1])/2
display(round(solar_data['cum_power'].mean(), 0))

23848.0

In [57]:
solar_data['date'] = pd.to_datetime(solar_data['date'])
solar_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664 entries, 0 to 663
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   date       664 non-null    datetime64[ns]
 1   cum_power  664 non-null    float64       
dtypes: datetime64[ns](1), float64(1)
memory usage: 10.5 KB


In [59]:
solar_data['year_month'] = solar_data['date'].dt.to_period('M')
display(solar_data)

date  cum_power year_month
0   2017-01-01    20111.0    2017-01
1   2017-01-02    20112.0    2017-01
2   2017-01-03    20115.0    2017-01
3   2017-01-04    20117.0    2017-01
4   2017-01-05    20119.0    2017-01
..         ...        ...        ...
659 2018-10-22    28101.0    2018-10
660 2018-10-23    28109.0    2018-10
661 2018-10-24    28115.0    2018-10
662 2018-10-25    28117.0    2018-10
663 2018-10-26    28120.0    2018-10

[664 rows x 3 columns]

In [62]:
display(solar_data[solar_data['year_month' == '2017-03']])

KeyError: False

In [ ]:
a = student_data[student_data['race/ethnicity'] == 'group A']['writing score'].median()

In [67]:
m = solar_data[solar_data['year_month'] == '2017-03']['cum_power'].mean()
print(round(m, 0))
print(m)

20445.0
20444.58064516129


In [68]:
solar_data['day_power'] = solar_data['cum_power'].diff()
display(solar_data)

date  cum_power year_month  day_power
0   2017-01-01    20111.0    2017-01        NaN
1   2017-01-02    20112.0    2017-01        1.0
2   2017-01-03    20115.0    2017-01        3.0
3   2017-01-04    20117.0    2017-01        2.0
4   2017-01-05    20119.0    2017-01        2.0
..         ...        ...        ...        ...
659 2018-10-22    28101.0    2018-10        6.0
660 2018-10-23    28109.0    2018-10        8.0
661 2018-10-24    28115.0    2018-10        6.0
662 2018-10-25    28117.0    2018-10        2.0
663 2018-10-26    28120.0    2018-10        3.0

[664 rows x 4 columns]

In [69]:
m = solar_data[solar_data['year_month'] == '2017-03']['day_power'].mean()
print(round(m, 0))
print(m)

11.0
10.774193548387096


In [71]:
#import matplotlib.pyplot as plt
#import seaborn as sns
import plotly.express as px
#from scipy import stats

In [73]:
"""bar_data = solar_data[solar_data['day_power'] >= 0].groupby('year_month', as_index=False).mean()
fig = px.bar(
    data_frame=bar_data,
    x='year_month',
    y='day_power',
    title='Средняя дневная выроботка по месяцам'
)
fig.show()"""

C:\Users\korol\AppData\Local\Temp\ipykernel_14248\3599442949.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  bar_data = solar_data[solar_data['day_power'] >= 0].groupby('year_month', as_index=False).mean()


TypeError: Object of type Period is not JSON serializable